all:
  hosts:
    media.local: 
      backup_name: plex
      backup_files_list: 
        - $(find "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases" -path "*com.plexapp.plugins.library.db-2*" -printf "%p\n" | sort -n | tail -1)
        - $(find "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases" -path "*com.plexapp.plugins.library.blobs.db-2*" -printf "%p\n" | sort -n | tail -1)
    docker.local: 
      backup_name: docker
      backup_files_list:
        - /opt
        - /var/lib/docker/volumes/portainer_data/_data
        - /var/lib/docker/volumes/miniflux_miniflux-db/_data
    unifi.local:
      backup_name: unifi
      backup_files_list:
        - $(find "/var/lib/unifi/backup/autobackup" -path "*autobackup*unf*" -printf "%p\n" | sort -n | tail -1)
    r2d2.local:
      backup_name: proxmox
      backup_files_list:
        - /etc/pve
        - /etc/network/interfaces
        - /etc/passwd
        - /etc/resolv.conf